language: node_js
sudo: false
node_js:
  - "10"

install:
  - npm i -g hexo-cli
  - npm ci

before_script:
  - git config --global user.name 'heycalmdown'
  - git config --global user.email 'heyacct@gmail.com'
  - sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script:
  - hexo generate
  - hexo deploy
