menu:
  Home: /
  Archives: /archives
  #About: /about
  #Tags: /tags
  # Categories: /categories



# Social links
social:
  GitHub:
    key: github
    link: https://github.com/heycalmdown

# disqus comment
disqus: false
disqus_shortname: 

# livere comment
livere: false
livere_uid: 

#Gitment (Recommended Use) see https://imsun.net/posts/gitment-introduction/
Gitment: false

# google analytics
googleTrackId: 

# google AdSenseId
AdSenseId: 

toc:
  enable: true

# anchorjs
anchorjs: true

# sidebar search
search: false
# sidebar categories
categories: true
# sidebar links
links: true


draw: false